version: "3"

services:
    app_increazy:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        tty: true
        expose:
          - "9000"
        ports:
            - "5173:5173"
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./.docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        container_name: app_increazy
        networks:
            - app-network-increazy

    webserver:
        image: nginx:alpine
        container_name: webserver
        restart: unless-stopped
        tty: true
        ports:
            - "8888:80"
        volumes:
            - ./:/var/www
            - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network-increazy

networks:
    app-network-increazy:
        driver: bridge
